version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Deployment package created successfully

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
